/** Configuration options for constructing automated fix pull request descriptions. */
export interface PRBodyOptions {
  /** Issue number being fixed (undefined when no linked issue exists). */
  issueNumber?: number;
  /** Title of the issue being fixed. */
  issueTitle: string;
  /** Summary of changes written to .fix-summary.md by the fix agent. */
  fixSummary?: string;
  /** Array of file paths changed by the fix. */
  filesChanged: string[];
  /** Branch name created for the fix PR. */
  branchName: string;
  /** Whether automated tests or verification checks were run. */
  hasTests?: boolean;
  /** Optional technical approach extracted from the analysis plan. */
  analysisApproach?: string;
}

/**
 * Build a structured, high-quality PR body for auto-created fix pull requests.
 * Replaces verbatim issue body copying with a real fix summary and file list.
 *
 * @param opts - PR body options.
 * @returns Markdown string for the PR description.
 */
export function buildAutofixPRBody(opts: PRBodyOptions): string {
  const lines: string[] = [];

  if (opts.issueNumber) {
    lines.push(`## Fixes #${opts.issueNumber}`);
    lines.push('');
  }

  lines.push('## What Was Changed');
  lines.push('');
  if (opts.fixSummary && opts.fixSummary.trim().length > 0) {
    lines.push(opts.fixSummary.trim());
  } else {
    lines.push('The fix agent applied changes to address the issue. See commit diff for details.');
  }
  lines.push('');

  if (opts.filesChanged.length > 0) {
    lines.push('## Files Changed');
    lines.push('');
    for (const f of opts.filesChanged) {
      lines.push(`- \`${f}\``);
    }
    lines.push('');
  }

  if (opts.analysisApproach && opts.analysisApproach.trim().length > 0) {
    lines.push('<details>');
    lines.push('<summary>Implementation Approach (from analysis)</summary>');
    lines.push('');
    lines.push(opts.analysisApproach.trim());
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push('## Test Plan');
  lines.push('');
  if (opts.hasTests) {
    lines.push('- Automated tests were run and passed');
    lines.push('- The fix was verified with project lint/typecheck commands');
  } else {
    lines.push('- Please verify the fix manually before merging');
    lines.push('- Run the test suite to confirm no regressions: `pnpm test`');
  }
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push(`*🤖 Auto-generated by opencode-ai-reviewer from branch \`${opts.branchName}\`.*`);

  return lines.join('\n');
}
