import type { DocStyle } from '../types/index.js';

/**
 * Escape backslashes and backticks in a file path so it renders as a single
 * inline code span even when the path contains either character.
 * @param file - File path to escape.
 * @returns The path with backslashes doubled and backticks escaped.
 */
function escapeCodeSpan(file: string): string {
  return file.replace(/\\/g, '\\\\').replace(/`/g, '\\`');
}

/**
 * Escape markdown metacharacters in untrusted user text (e.g. a source PR
 * title) so it cannot break out of prose or inject links, images, or code
 * spans into the auto-created docs PR body.
 * @param text - Untrusted text.
 * @returns The text with markdown metacharacters backslash-escaped.
 */
function escapeMarkdownText(text: string): string {
  return text.replace(/([`*_\[\]()#!<>~|\\])/g, '\\$1');
}

/** Configuration options for constructing automated fix pull request descriptions. */
export interface PRBodyOptions {
  /** Issue number being fixed (undefined when no linked issue exists). */
  issueNumber?: number;
  /** Title of the issue being fixed. */
  issueTitle: string;
  /** Summary of changes written to .fix-summary.md by the fix agent. */
  fixSummary?: string;
  /** Array of file paths changed by the fix. */
  filesChanged: string[];
  /** Branch name created for the fix PR. */
  branchName: string;
  /** Whether automated tests or verification checks were run. */
  hasTests?: boolean;
  /** Optional technical approach extracted from the analysis plan. */
  analysisApproach?: string;
}

/**
 * Build a structured, high-quality PR body for auto-created fix pull requests.
 * Replaces verbatim issue body copying with a real fix summary and file list.
 *
 * @param opts - PR body options.
 * @returns Markdown string for the PR description.
 */
export function buildAutofixPRBody(opts: PRBodyOptions): string {
  const lines: string[] = [];

  if (opts.issueNumber) {
    lines.push(`## Fixes #${opts.issueNumber}`);
    lines.push('');
  }

  lines.push('## What Was Changed');
  lines.push('');
  if (opts.fixSummary && opts.fixSummary.trim().length > 0) {
    lines.push(opts.fixSummary.trim());
  } else {
    lines.push('The fix agent applied changes to address the issue. See commit diff for details.');
  }
  lines.push('');

  if (opts.filesChanged.length > 0) {
    lines.push('## Files Changed');
    lines.push('');
    for (const f of opts.filesChanged) {
      lines.push(`- \`${f}\``);
    }
    lines.push('');
  }

  if (opts.analysisApproach && opts.analysisApproach.trim().length > 0) {
    lines.push('<details>');
    lines.push('<summary>Implementation Approach (from analysis)</summary>');
    lines.push('');
    lines.push(opts.analysisApproach.trim());
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push('## Test Plan');
  lines.push('');
  if (opts.hasTests) {
    lines.push('- Automated tests were run and passed');
    lines.push('- The fix was verified with project lint/typecheck commands');
  } else {
    lines.push('- Please verify the fix manually before merging');
    lines.push('- Run the test suite to confirm no regressions: `pnpm test`');
  }
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push(`*🤖 Auto-generated by opencode-ai-reviewer from branch \`${opts.branchName}\`.*`);

  return lines.join('\n');
}

/** Options for constructing documentation pull request descriptions. */
export interface DocsPRBodyOptions {
  /** Source PR number being documented. */
  prNumber: number;
  /** Title of the source PR being documented. */
  prTitle: string;
  /** Summary of the documentation written to .docs-summary.md. */
  docsSummary?: string;
  /** Array of file paths that received documentation. */
  filesChanged: string[];
  /** Branch name created for the docs PR. */
  branchName: string;
  /** Doc style used for the generated comments. */
  docStyle?: DocStyle;
}

/**
 * Build a structured PR body for auto-created documentation pull requests.
 * Describes which PR's changed code was documented and which files were touched.
 *
 * @param opts - Docs PR body options.
 * @returns Markdown string for the PR description.
 */
export function buildDocsPRBody(opts: DocsPRBodyOptions): string {
  const lines: string[] = [];

  lines.push(`## Adds documentation for #${opts.prNumber}`);
  lines.push('');
  lines.push(
    `This PR adds documentation comments for the code changed in PR #${opts.prNumber} ("${escapeMarkdownText(opts.prTitle)}").`,
  );
  lines.push('');

  lines.push('## What Was Documented');
  lines.push('');
  if (opts.docsSummary && opts.docsSummary.trim().length > 0) {
    lines.push(opts.docsSummary.trim());
  } else {
    lines.push(
      'The documentation agent added doc comments to the code changed in the source PR. See the commit diff for details.',
    );
  }
  lines.push('');

  if (opts.filesChanged.length > 0) {
    lines.push('## Files Changed');
    lines.push('');
    for (const f of opts.filesChanged) {
      lines.push(`- \`${escapeCodeSpan(f)}\``);
    }
    lines.push('');
  }

  if (opts.docStyle && opts.docStyle !== 'auto') {
    lines.push('## Doc Style');
    lines.push('');
    lines.push(
      `Generated using the \`${opts.docStyle}\` style (existing per-file conventions take precedence where present).`,
    );
    lines.push('');
  }

  lines.push('## Test Plan');
  lines.push('');
  lines.push('- Please verify the documentation renders correctly before merging');
  lines.push('- No behavior or logic changes are included in this PR');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`*🤖 Auto-generated by opencode-ai-reviewer from branch \`${opts.branchName}\`.*`);

  return lines.join('\n');
}
