import * as core from '@actions/core';
import * as exec from '@actions/exec';
import * as github from '@actions/github';
import type {
  AgentConfig,
  FixResult,
  GitHubHelper,
  ReviewEngine,
  ReviewResult,
} from '@opencode-pr-agent/lib';
import type { ActionInputs } from './inputs.js';

export async function runFix(
  inputs: ActionInputs,
  config: AgentConfig,
  engine: ReviewEngine,
  gh: GitHubHelper,
  _repo: string,
  _token: string,
): Promise<void> {
  const prNumber = await resolvePrNumber();
  if (prNumber === null) {
    core.setFailed('Could not determine PR number for fix');
    return;
  }

  const comments = await gh.getIssueComments(prNumber);
  const iteration = comments.filter((c) => c.body.includes('<!-- autofix-review -->')).length;

  if (iteration >= config.maxIterations) {
    core.warning(`Max iterations reached (${config.maxIterations}). Needs manual review.`);
    await gh.setLabels(prNumber, ['autofix:needs-manual-review'], ['autofix', 'autofix:needs-fix']);
    return;
  }

  const pr = await gh.getPR(prNumber);
  const contextMarkdown = await gh.gatherContext({ prNumber });

  const fixResult = await engine.runFix(prNumber, iteration, contextMarkdown, pr);

  let changesMade = false;
  if (fixResult.changesMade) {
    await exec.exec('git', ['add', '-A']);
    await exec.exec('git', [
      'commit',
      '-m',
      `fix: address review feedback (iteration ${iteration + 1})`,
    ]);
    await exec.exec('git', ['push', 'origin', pr.headRef]);
    changesMade = true;
  }

  if (inputs.runChecksAfterFix && changesMade) {
    core.info('Running verification commands...');
    try {
      await exec.exec('bash', ['-c', inputs.runChecksAfterFix]);
    } catch (error) {
      core.warning(`Verification command failed: ${inputs.runChecksAfterFix} — ${String(error)}`);
    }
  }

  await gh.removeLabel(prNumber, 'autofix:needs-fix');

  core.setOutput('changes_made', String(changesMade));
}

export async function runFixIssue(
  _inputs: ActionInputs,
  _config: AgentConfig,
  engine: ReviewEngine,
  gh: GitHubHelper,
  repo: string,
  token: string,
): Promise<void> {
  const issueNumber = github.context.payload.issue?.number;
  if (!issueNumber) {
    core.setFailed('Could not determine issue number');
    return;
  }

  core.info(`Fixing issue #${issueNumber}`);

  const branchName = `autofix/issue-${issueNumber}`;

  const existingRef = await exec
    .getExecOutput('git', ['rev-parse', '--verify', branchName], { ignoreReturnCode: true })
    .catch(() => ({ exitCode: 1, stdout: '', stderr: '' }));

  if (existingRef.exitCode === 0) {
    await exec.exec('git', ['checkout', branchName]);
  } else {
    await exec.exec('git', ['checkout', '-b', branchName]);
  }

  const issueContext = await gh.gatherContext({ issueNumber });

  const fixResult = await engine.runFix(issueNumber, 0, issueContext);

  if (!fixResult.changesMade) {
    core.info('No changes made by fix agent');
    return;
  }

  const hasChanges = await exec
    .getExecOutput('git', ['status', '--porcelain'])
    .then((r) => r.stdout.trim().length > 0);

  if (!hasChanges) {
    core.info('No file changes to commit');
    return;
  }

  await exec.exec('git', ['add', '-A']);
  await exec.exec('git', ['commit', '-m', `fix: address issue #${issueNumber}`]);
  await exec.exec('git', ['push', 'origin', branchName, '--force']);

  const issue = await gh.getIssue(issueNumber);
  const prTitle = `[Autofix] ${issue.title}`;

  const prBody = `## Fixes #${issueNumber}\n\n${issue.body}\n\n---\n*Auto-generated by opencode-ai-reviewer*`;

  // Ensure the autofix label exists in the repository before referencing it in pr create
  await gh.ensureLabels(['autofix']);

  const prUrl = await exec
    .getExecOutput(
      'gh',
      [
        'pr',
        'create',
        '--base',
        'main',
        '--head',
        branchName,
        '--title',
        prTitle,
        '--body',
        prBody,
        '--label',
        'autofix',
        '--repo',
        repo,
      ],
      {
        env: { ...process.env, GH_TOKEN: token } as { [key: string]: string },
      },
    )
    .then((r) => r.stdout.trim());

  core.info(`Created PR: ${prUrl}`);
  core.setOutput('pr_url', prUrl);

  await gh.postOrUpdateComment(issueNumber, '<!-- autofix-pr-link -->', `🔧 Autofix PR: ${prUrl}`);

  core.setOutput('changes_made', 'true');
}

interface IterationRecord {
  iteration: number;
  status: 'approved' | 'fix-applied' | 'needs-fix' | 'no-changes';
  summary: string;
  critical: number;
  important: number;
  minor: number;
  filesChanged?: string[];
  commitMessage?: string;
}

const REVIEW_MARKER = '<!-- autofix-review -->';
const FIX_MARKER = '<!-- autofix-applied -->';
const _MERGE_MARKER = '<!-- autofix-merged -->';

function buildReviewBody(
  history: IterationRecord[],
  maxIterations: number,
  phase: 'reviewing' | 'approved' | 'no-changes' | 'max-iterations',
  current?: ReviewResult,
): string {
  const lines: string[] = ['## 🤖 Autofix Review', ''];
  const currentIter = history.length;

  switch (phase) {
    case 'reviewing':
      lines.push(`**Status:** 🔍 Reviewing (iteration ${currentIter}/${maxIterations})`);
      break;
    case 'approved':
      lines.push('**Status:** ✅ Approved — all issues resolved');
      break;
    case 'no-changes':
      lines.push(
        `**Status:** ℹ️ Fix agent made no changes (iteration ${currentIter}/${maxIterations})`,
      );
      break;
    case 'max-iterations':
      lines.push('**Status:** ⚠️ Manual review required');
      break;
  }

  if (current) {
    if (current.summary) {
      lines.push('', '### Summary', '', current.summary);
    }
    if (current.issues.length > 0) {
      lines.push('', '### Issues Found');
      for (const i of current.issues) {
        lines.push(`- **${i.severity.toUpperCase()}:** ${i.file}:${i.line} — ${i.message}`);
        if (i.suggestion) lines.push(`  > ${i.suggestion}`);
      }
    }
    if (current.strengths.length > 0) {
      lines.push('', '### Strengths');
      for (const s of current.strengths) {
        lines.push(`- ✅ **${s.file}:${s.line}** — ${s.message}`);
      }
    }
  }

  if (history.length > 0) {
    lines.push('', '### Iteration History');
    for (const h of history) {
      let icon: string;
      let detail: string;
      switch (h.status) {
        case 'approved':
          icon = '✅';
          detail = 'All issues resolved';
          break;
        case 'fix-applied':
          icon = '🔧';
          detail = `Fix applied — ${h.critical} critical, ${h.important} important`;
          break;
        case 'needs-fix':
          icon = '❌';
          detail = `${h.critical} critical, ${h.important} important remaining`;
          break;
        case 'no-changes':
          icon = 'ℹ️';
          detail = 'No changes made';
          break;
      }
      lines.push(`- ${icon} **Iteration ${h.iteration}:** ${detail}`);
    }
  }

  switch (phase) {
    case 'approved':
      lines.push('', '✅ **Ready to merge!**');
      break;
    case 'max-iterations':
      lines.push(
        '',
        `⚠️ **Max iterations reached (${maxIterations}).** This PR needs manual review.`,
      );
      break;
  }

  return lines.join('\n');
}

function buildFixBody(history: IterationRecord[]): string {
  const last = history[history.length - 1];
  const lines: string[] = ['## 🔧 Autofix Applied', ''];

  if (last) {
    lines.push(`**Iteration:** ${last.iteration}`);
    lines.push(`**Files changed:** ${last.filesChanged?.length ?? 0}`);
    if (last.commitMessage) lines.push(`**Commit:** \`${last.commitMessage}\``);
    if (last.filesChanged && last.filesChanged.length > 0) {
      lines.push('', '### Changed Files');
      for (const f of last.filesChanged) {
        lines.push(`- \`${f}\``);
      }
    }
  }

  lines.push(
    '',
    '---',
    '',
    '🤖 The fix agent has applied changes. The PR will be reviewed again on the next iteration.',
  );
  return lines.join('\n');
}

function buildReadyBody(history: IterationRecord[], prNumber: number): string {
  const lines: string[] = ['## ✅ Ready to Merge', ''];
  lines.push(`All issues have been resolved in PR #${prNumber}.`);
  lines.push(
    '',
    'The review agent has approved this PR. A maintainer can merge it at their discretion.',
  );
  if (history.length > 0) {
    lines.push('', '### Summary');
    for (const h of history) {
      if (h.summary) {
        lines.push('', h.summary);
        break;
      }
    }
  }
  return lines.join('\n');
}

export async function runAutofixLoop(
  inputs: ActionInputs,
  config: AgentConfig,
  engine: ReviewEngine,
  gh: GitHubHelper,
  _repo: string,
  _token: string,
): Promise<void> {
  const prNumber = await resolvePrNumber();
  if (prNumber === null) {
    core.setFailed('Could not determine PR number for autofix loop');
    return;
  }

  const history: IterationRecord[] = [];
  let approved = false;

  for (let i = 0; i < config.maxIterations; i++) {
    core.info(`=== Autofix iteration ${i + 1}/${config.maxIterations} ===`);

    const pr = await gh.getPR(prNumber);
    const result = await engine.reviewPR(pr, i, inputs.reviewPromptFile, inputs.reviewPromptExtra);

    const entry: IterationRecord = {
      iteration: i + 1,
      status: 'approved',
      summary: result.summary,
      critical: result.stats.critical,
      important: result.stats.important,
      minor: result.stats.minor,
    };

    if (result.verdict.ready && result.stats.critical === 0 && result.stats.important === 0) {
      core.info('PR approved — all issues resolved');
      approved = true;
      entry.status = 'approved';
      history.push(entry);

      await gh.setLabels(prNumber, ['autofix:ready'], ['autofix', 'autofix:needs-fix']);
      await gh.createComment(prNumber, buildReadyBody(history, prNumber));
      core.info('Posted ready-to-merge notification');
      break;
    }

    entry.status = 'needs-fix';
    entry.summary = result.summary;
    history.push(entry);
    await gh.postOrUpdateComment(
      prNumber,
      REVIEW_MARKER,
      buildReviewBody(history, config.maxIterations, 'reviewing', result),
    );

    const contextMarkdown = await gh.gatherContext({ prNumber });
    const fixResult = await engine.runFix(prNumber, i, contextMarkdown, pr);

    if (!fixResult.changesMade) {
      core.info('Fix agent made no changes — stopping loop');
      history[history.length - 1].status = 'no-changes';
      await gh.postOrUpdateComment(
        prNumber,
        REVIEW_MARKER,
        buildReviewBody(history, config.maxIterations, 'no-changes', result),
      );
      break;
    }

    history[history.length - 1].status = 'fix-applied';
    history[history.length - 1].filesChanged = fixResult.filesChanged;
    history[history.length - 1].commitMessage = fixResult.commitMessage;

    await exec.exec('git', ['add', '-A']);
    await exec.exec('git', ['commit', '-m', `fix: autofix iteration ${i + 1}`]);
    await exec.exec('git', ['push', 'origin', pr.headRef]);

    await gh.postOrUpdateComment(prNumber, FIX_MARKER, buildFixBody(history));

    if (inputs.runChecksAfterFix) {
      core.info('Running verification commands...');
      try {
        await exec.exec('bash', ['-c', inputs.runChecksAfterFix]);
      } catch (error) {
        core.warning(`Verification command failed: ${inputs.runChecksAfterFix} — ${String(error)}`);
      }
    }
  }

  if (!approved) {
    core.warning(
      `Max iterations reached (${config.maxIterations}) or agent not approved. Needs manual review.`,
    );
    await gh.setLabels(prNumber, ['autofix:needs-manual-review'], ['autofix', 'autofix:needs-fix']);
    await gh.postOrUpdateComment(
      prNumber,
      REVIEW_MARKER,
      buildReviewBody(history, config.maxIterations, 'max-iterations'),
    );
  }

  core.setOutput('approved', String(approved));
}

async function resolvePrNumber(): Promise<number | null> {
  const prNumberInput = core.getInput('pr-number');
  if (prNumberInput) {
    return Number.parseInt(prNumberInput, 10);
  }
  const fromIssue = github.context.payload.issue?.number;
  const fromPR = github.context.payload.pull_request?.number;
  return fromPR || fromIssue || null;
}
