import { execFileSync } from 'child_process';
import type { AgentConfig } from '@opencode-pr-agent/lib';
import { GitHubHelper, Logger, ReviewEngine, configureGit } from '@opencode-pr-agent/lib';
import { handleAudit } from './audit.js';
import { handleAutofixLoop } from './autofix.js';
import { handlePRReview } from './pr-review.js';

export async function handleCommand(
  command: 'fix' | 'review' | 'audit',
  issueNumber: number,
  repo: string,
  token: string,
  config: AgentConfig,
): Promise<void> {
  const logger = new Logger('Command', { repo, prNumber: issueNumber });
  const gh = new GitHubHelper(token, repo);

  try {
    switch (command) {
      case 'review': {
        if (await gh.isPR(issueNumber)) {
          await handlePRReview(issueNumber, repo, token, config);
        }
        break;
      }

      case 'fix': {
        const existingPR = await findExistingAutofixPR(gh, issueNumber);
        if (existingPR) {
          await handleAutofixLoop(existingPR, repo, token, config);
        } else {
          await createAutofixPR(gh, issueNumber, repo, token, config);
        }
        break;
      }

      case 'audit': {
        await handleAudit(repo, token, config);
        break;
      }
    }
  } catch (err) {
    logger.error(
      `Command ${command} failed for issue ${issueNumber} in ${repo}: ${err instanceof Error ? err.message : err}`,
    );
  }
}

async function findExistingAutofixPR(
  gh: GitHubHelper,
  issueNumber: number,
): Promise<number | null> {
  const logger = new Logger('Command', { prNumber: issueNumber });
  try {
    const issue = await gh.getIssue(issueNumber);
    const prLink = issue.body?.match(/PR #(\d+)/)?.[1];
    if (prLink) return Number.parseInt(prLink, 10);
  } catch (err) {
    logger.debug(
      `Failed to find existing autofix PR for issue ${issueNumber}: ${err instanceof Error ? err.message : err}`,
    );
  }
  return null;
}

async function createAutofixPR(
  gh: GitHubHelper,
  issueNumber: number,
  repo: string,
  token: string,
  config: AgentConfig,
): Promise<void> {
  const logger = new Logger('Command', { repo, prNumber: issueNumber });
  logger.info(`Fix triggered for issue #${issueNumber}`);

  configureGit('opencode-pr-agent[bot]', 'opencode-pr-agent[bot]@users.noreply.github.com', token);

  const engine = new ReviewEngine(config, token, repo);
  const branchName = `autofix/issue-${issueNumber}`;

  try {
    // Fetch latest from origin
    execFileSync('git', ['fetch', 'origin'], { stdio: 'pipe' });

    // Check if branch already exists locally
    let branchExists = false;
    try {
      execFileSync('git', ['rev-parse', '--verify', branchName], { stdio: 'pipe' });
      branchExists = true;
    } catch {
      branchExists = false;
    }

    const defaultBranch = await gh.getDefaultBranch();

    if (branchExists) {
      execFileSync('git', ['checkout', branchName]);
      logger.info(`Checked out existing branch ${branchName}`);
    } else {
      execFileSync('git', ['checkout', '-b', branchName, `origin/${defaultBranch}`]);
      logger.info(`Created branch ${branchName} from ${defaultBranch}`);
    }

    // Gather issue context
    const issueContext = await gh.gatherContext({ issueNumber });

    // Run the fix engine
    const fixResult = await engine.runFix(issueNumber, 0, issueContext);

    if (!fixResult?.changesMade) {
      logger.info('No changes made by fix agent — no PR will be created');
      await engine.cleanup();
      return;
    }

    // Commit and push changes
    execFileSync('git', ['add', '-A']);
    execFileSync('git', ['commit', '-m', `fix: address issue #${issueNumber}`]);

    try {
      execFileSync('git', ['push', 'origin', branchName, '--force']);
    } catch (err) {
      logger.error(`Git push failed: ${err instanceof Error ? err.message : err}`);
      await engine.cleanup();
      return;
    }

    // Get issue info for PR title
    const issue = await gh.getIssue(issueNumber);
    const prTitle = `[Autofix] ${issue.title}`;
    const prBody = `## Fixes #${issueNumber}\n\n${issue.body}\n\n---\n*Auto-generated by opencode-ai-reviewer*`;

    // Ensure the autofix label exists in the repository
    await gh.ensureLabels(['autofix']);

    // Create PR
    const pr = await gh.createPR(prTitle, prBody, branchName, defaultBranch);
    if (pr) {
      logger.info(`Created PR #${pr.number}: ${pr.url}`);
      // Post comment on the issue linking the PR
      try {
        await gh.postOrUpdateComment(
          issueNumber,
          '<!-- autofix-pr-link -->',
          `🔧 Autofix PR: ${pr.url}`,
        );
      } catch (err) {
        logger.warn(
          `Failed to post autofix PR link comment: ${err instanceof Error ? err.message : err}`,
        );
      }
    }
  } catch (err) {
    logger.error(
      `Autofix PR creation failed for issue #${issueNumber}: ${err instanceof Error ? err.message : err}`,
    );
  } finally {
    await engine.cleanup();
  }
}
